"""fix_missing_contact_columns

Revision ID: cb4eb62e7457
Revises: f15930b3fb04
Create Date: 2026-05-17 05:09:05.914319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4eb62e7457'
down_revision = 'f15930b3fb04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('is_group', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('contacts', sa.Column('group_jid', sa.String(length=256), nullable=True))
    op.add_column('contacts', sa.Column('avg_response_hours', sa.Float(), nullable=True))
    op.add_column('contacts', sa.Column('last_outbound_at', sa.DateTime(), nullable=True))
    op.add_column('notes', sa.Column('pinned', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('notes', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('reminders', sa.Column('repeat', sa.String(length=32), nullable=True))
    op.add_column('telegram_sessions', sa.Column('last_sender_id', sa.String(length=256), nullable=True))
    op.add_column('telegram_sessions', sa.Column('last_sender_name', sa.String(length=256), nullable=True))
    op.add_column('telegram_sessions', sa.Column('last_thread_id', sa.String(length=512), nullable=True))
    op.add_column('user_profile', sa.Column('draft_mode', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'draft_mode')
    op.drop_column('telegram_sessions', 'last_thread_id')
    op.drop_column('telegram_sessions', 'last_sender_name')
    op.drop_column('telegram_sessions', 'last_sender_id')
    op.drop_column('reminders', 'repeat')
    op.drop_column('notes', 'updated_at')
    op.drop_column('notes', 'pinned')
    op.drop_column('contacts', 'last_outbound_at')
    op.drop_column('contacts', 'avg_response_hours')
    op.drop_column('contacts', 'group_jid')
    op.drop_column('contacts', 'is_group')
    # ### end Alembic commands ###
