"""Added memory models

Revision ID: dac93c407f2a
Revises: 
Create Date: 2026-05-14 08:03:17.495477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac93c407f2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_key', sa.String(length=256), nullable=False),
    sa.Column('fact', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_message_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('client_name', sa.String(length=256), nullable=True),
    sa.Column('tone', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('work_context', sa.Text(), nullable=True),
    sa.Column('active_hours_start', sa.Integer(), nullable=False),
    sa.Column('active_hours_end', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('reply_format', sa.String(length=64), nullable=False),
    sa.Column('extra_prefs', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('contacts', sa.Column('nickname', sa.String(length=256), nullable=True))
    op.add_column('contacts', sa.Column('relationship_type', sa.String(length=64), nullable=True))
    op.add_column('contacts', sa.Column('writing_style', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False))
    op.add_column('contacts', sa.Column('importance_override', sa.Integer(), nullable=True))
    op.add_column('contacts', sa.Column('muted_until', sa.DateTime(), nullable=True))
    op.add_column('contacts', sa.Column('style_sample_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'style_sample_count')
    op.drop_column('contacts', 'muted_until')
    op.drop_column('contacts', 'importance_override')
    op.drop_column('contacts', 'writing_style')
    op.drop_column('contacts', 'relationship_type')
    op.drop_column('contacts', 'nickname')
    op.drop_table('user_profile')
    op.drop_table('memories')
    op.drop_table('conversation_turns')
    # ### end Alembic commands ###
