"""Add contact_id to ConversationTurn

Revision ID: f15930b3fb04
Revises: dac93c407f2a
Create Date: 2026-05-14 08:12:07.398069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15930b3fb04'
down_revision = 'dac93c407f2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_turns', sa.Column('contact_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_turns', 'contact_id')
    # ### end Alembic commands ###
